In [ ]:
# =============================================================================
#
# Pronostico time trend + fourier seasonal
#
# =============================================================================

#
# Carga de datos
#
import nbimporter  #  type: ignore
import functions  #  type: ignore


df_orig = functions.load_data()
df_orig.head()

            yt_true
date
1946-01-01      890
1946-02-01      992
1946-03-01      979
1946-04-01      959
1946-05-01     1110

In [ ]:



#
# Componentes de tendencia lineal
#
df_orig = functions.add_linear_trend_component(df_orig)
df_orig = functions.add_month_component(df_orig)
df_orig.head()

            yt_true  trend  month
date
1946-01-01      890      0      1
1946-02-01      992      1      2
1946-03-01      979      2      3
1946-04-01      959      3      4
1946-05-01     1110      4      5